language: java
jdk:
- openjdk8
branches:
  - develop
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --info"

# CI 실행 완료시 슬랙 알림
notifications:
  slack:
    secure: Uba/MxcK6LPlhYmQjXHy5aw0fe/cRRRQVlgdi7E6hxnYH3AaR8G8DzptUehvwEnuldol81SwlVgTt84VFHQ4L3JOhznqaQUaeQ4JZCyb/1z9M3FCtVqps8D9aMLS0ZXiuiRLzwrqhKxTO7Kll3OYMQyk01hdFZLkEler4NRXiDUTFnU664EzWh44FCq+OttAI/+Vmcs6lptast9/lp/uqeASKVmEoTivYA1dNbCdRoKhJZzJbNUNAkmIbad4iYbr1Q1xdqZUXlYrsNhVa1AKC2poTOdwkgn2ir37xsfjEQ3dQD6/AP4a9O2NWJBpBqEuyYkjxnJRsEGqp5zt7k37SCgdTLObrOF53rfnrkNtDniP1nVpfTU7XJ1APZ6uparGgs4JYOKRU5/xBuf4OOdI5ngrGFC57D/ePd+hdMjE1AfzFJ4kJRviy/NaBstMV9pNdJiBBJqSig7/gwGfSsyBAY9hGby4AUXBxi2N6g4G2EyGKrp3X/ODrSKUHpBfWKVJZkvjpaLsD5hlkO7gKVHpAhjHQoz4lX0MucpLR5M9PYZA6CMLyugoTF6OtcTzXYOnm9GfVL6b0/RfccPDepGeIjkP8vvbPqz/I7Iqe87p4tUx3HdLtkJcgEGcg7ex1dWp2fViGStRMCeA+Zj0Ou+DYPHAO//glezgh1ezZs8zsfY=

services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

before_install:
- mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root';"
- mysql -e "use mysql; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
- mysql_upgrade
- sudo service mysql restart
- mysql -e 'CREATE DATABASE IF NOT EXISTS woowanote CHARACTER SET utf8 COLLATE utf8_general_ci;'
- mysql -e "CREATE USER 'team1'@'%' IDENTIFIED BY 'team1';"
- mysql -e "GRANT ALL PRIVILEGES ON woowanote.* TO 'team1'@'%'; FLUSH PRIVILEGES;";

deploy:
  - provider: s3
    access_key_id: $AWS_DEPLOY_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_DEPLOY_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: woowanote-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: wwh-techcamp-2018/team1-WannaOne #Github 주소
      branch: master