language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -Pprofile=build --stacktrace --debug"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dain7672@naver.com

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE woowanote;'