language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dain7672@naver.com

services:
- mysql

sudo: true

before_script:
- chmod +x ./travis/*
- ./travis/mysql-version-upgrade.sh
- ./travis/mysql-reset-root-password.sh
- ./travis/mysql-create-test-database.sh
- ./travis/mysql-create-user.sh