language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dain7672@naver.com

services:
    - mysql
    
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart
- mysql -u root -e 'CREATE DATABASE IF NOT EXISTS woowanote;'
- mysql -u root -e "CREATE USER 'team1'@'%' IDENTIFIED BY 'team1;"
- mysql -u root -e "GRANT ALL PRIVILEGES ON woowanote.* TO 'team1'@'%';";
- mysql -u root -e "FLUSH PRIVILEGES";

