language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

script: "./gradlew clean build --stacktrace --info"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dain7672@naver.com

services:
    - mysql

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

before_install:
- mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root';"
- mysql -e "use mysql; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
- mysql_upgrade
- sudo service mysql restart
- sudo mysql -e 'CREATE DATABASE IF NOT EXISTS woowanote;'
- sudo mysql -e "CREATE USER 'team1'@'%' IDENTIFIED BY 'team1';"
- sudo mysql -e "GRANT ALL PRIVILEGES ON woowanote.* TO 'team1'@'%'; FLUSH PRIVILEGES;";

