language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

script: "./gradlew clean build --stacktrace --info"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dain7672@naver.com

services:
    - mysql

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

before_install:
- mysql -e 'create database woowanote;'
